apiVersion: v1
kind: Service
metadata:
  name: helloworld2
  namespace: sample
  labels:
    app: helloworld2
    service: helloworld2
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld2-c3z1
  namespace: sample
  labels:
    app: helloworld2
    version: c3z1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld2
      version: c3z1
  template:
    metadata:
      labels:
        app: helloworld2
        version: c3z1
    spec:
      containers:
      - name: helloworld2
        env:
        - name: SERVICE_VERSION
          value: c3z1
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
      nodeSelector:
        topology.kubernetes.io/zone: zone1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld2-c3z2
  namespace: sample
  labels:
    app: helloworld2
    version: c3z2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld2
      version: c3z2
  template:
    metadata:
      labels:
        app: helloworld2
        version: c3z2
    spec:
      containers:
      - name: helloworld2
        env:
        - name: SERVICE_VERSION
          value: c3z2
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      nodeSelector:
        topology.kubernetes.io/zone: zone2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld2-c3z3
  namespace: sample
  labels:
    app: helloworld2
    version: c3z3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld2
      version: c3z3
  template:
    metadata:
      labels:
        app: helloworld2
        version: c3z3
    spec:
      containers:
      - name: helloworld2
        env:
        - name: SERVICE_VERSION
          value: c3z3
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      nodeSelector:
        topology.kubernetes.io/zone: zone3
